on:
  issues:
    types:
      - labeled
      - edited

jobs:
  issue_to_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: eunjae-lee/issue-to-markdown@v0
        with:
          token: ${{ secrets.PAT }}
          dest: 'apps/web/content/blog'
          extension: '.svx'
          inject_created_at: true
          inject_created_at_key: createdAt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update contents'
